### ISSUE TITLE
build fails with musl target

### ISSUE THREAD

**Issue by opensourcegeek** [rethinkdb-rs/reql#14]
When I run `cargo build --target i686-unknown-linux-musl` I get the following error

error[E0463]: can't find crate for `proc_macro`
   --> /home/opensourcegeek/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-hack-0.3.3/src/lib.rs:159:1
    |
159 | extern crate proc_macro;
    | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

Seems like proc-macro-hack depends on proc_macro crate - I cannot find it in crates.io, there is only proc-macro2. I'm not sure how the build works fine on gnu target, I'll dig more but thought I'll report here as well.

**Comment by rushmorem** [comment]
Which version of `rustc` are you running? We currently test on `v1.17.0` and above but the `proc_macro` crate should be available from `v1.15.0` IIRC.

**Comment by rushmorem** [comment]
@opensourcegeek According to https://github.com/dtolnay/proc-macro-hack/issues/6#issuecomment-283518840 we need to disable `default-features` for `proc-macro-hack` to fix this.

**Comment by opensourcegeek** [comment]
@rushmorem Thanks - I've forked the project and disabled default features and it seems to work.

**Comment by rushmorem** [comment]
Thanks for the feedback. I'm reopening since the fix hasn't been applied to this repo yet. Mind submitting a pull request with your changes?

**Comment by rushmorem** [comment]
Now fixed in version 0.0.10.
