### ISSUE TITLE
Some information on filter

### ISSUE THREAD

**Issue by tavurth** [rethinkdb-rs/reql#18]
So I'm trying to write a simple filter to expand the changelog example so that it notes only changes which match our TestItem implementation, however I can't seem to get any filters working:

```rust
let query =
        r.db("test")
        .table("test")
        .filter(|doc| {
            doc.has_fields("test").and(doc.test.type_of("NUMBER"))
        })
        .changes()
```

Gives me:
```
error[E0619]: the type of this value must be known in this context
 |
 | .filter(|doc| { doc.has_fields("test").and(doc.test.type_of("NUMBER")) })
 |                 ^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `[closure@src/main.rs:55:17: 55:81]: reql::IntoArg` is not satisfied
 |
 |.filter(|doc| { doc.has_fields("test").and(doc.test.type_of("NUMBER")) })
 | ^^^^^^ the trait `reql::IntoArg` is not implemented for `[closure@src/main.rs:55:17: 55:81]`
```

Any advice on the filter implementation would be appreciated, I'm rather new to Rust at this point.

**Comment by rushmorem** [comment]
ReQL closures can take multiple arguments. We can't reasonably implement all the possibilities using Rust's type system. Combined with the fact that ReQL has so many commands, I decided to generate the commands automatically straight from the ReQL documentation. To make this possible, I made the following design choices:-

- Any command which takes __zero or more__ arguments is generated as taking _no arguments_
- Any command which takes __at least one__ argument is generated as taking _just 1 argument_

The argument that the command takes must implement `reql::IntoArg`. As you can see from the second error message, we don't implement it for closures as this is not practical. Instead we use the `args` macro to pass in closures. So try this instead:-

```rust
let query =
        r.db("test")
        .table("test")
        .filter(args!(|doc| {
            doc.has_fields("test").and(doc.get_field("test").type_of("NUMBER"))
        }))
        .changes()
```

You should also use the `args` macro to pass in at least one argument.

**Comment by tavurth** [comment]
I see, that makes a lot more sense now, thank you!

I've updated the example code to reflect the filtered change.

**Comment by rushmorem** [comment]
> I see, that makes a lot more sense now, thank you!

My pleasure :)

> I've updated the example code to reflect the filtered change.

Awesome! Let me take a look. Thanks.
