### ISSUE TITLE
Crates build status is "unknown"

### ISSUE THREAD

**Issue by tavurth** [rethinkdb-rs/reql#21]
After changing the group name today, the [crates.io](https://crates.io/crates/reql) build status is shown as "Unknown".

It's still pointing to the [rust-rethinkdb](https://travis-ci.org/rust-rethinkdb/reql) naming on travis.

**Comment by rushmorem** [comment]
I had already updated this in the `Cargo.toml` but since we haven't pushed a new release yet, crates.io is still pointing to the old organisation. I didn't think the changes on master so far warranted a new release but let me push anyway just so we can fix this.

**Comment by rushmorem** [comment]
Fixed in [v0.0.9](https://crates.io/crates/reql/0.0.9). Thanks!
