### ISSUE TITLE
RebirthDB

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb-rs/reql#25]
Hey, listen! I don't know if your driver already supports fully the 2.3 version, but we've forked RethinkDB to release a 2.4 version and all drivers will have separate repositories under our organization, discussion here: https://spectrum.chat/rebirthdb

So I'm inviting you to join us, there you can have more visibility for your project, what do you think?

**Comment by rushmorem** [comment]
> I don't know if your driver already supports fully the 2.3 version

Not yet. It's still a work in progress and far from production ready.

> but we've forked RethinkDB to release a 2.4 version

Yeah, I noticed that a few days back on the RethinkDB repo. As a RethinkDB user, I greatly appreciate all your efforts in that endeavor.

> all drivers will have separate repositories under our organization... So I'm inviting you to join us, there you can have more visibility for your project, what do you think?

If you are willing to also house drivers that are not yet production ready, I don't mind.

**Comment by thelinuxlich** [comment]
Yes, we(RebirthDB) want to attract newcomers from every language

**Comment by thelinuxlich** [comment]
I will add you as a member of the org

**Comment by rushmorem** [comment]
OK, great.

**Comment by rushmorem** [comment]
I've joined. Thanks.
