### ISSUE TITLE
How do I do multi document insert?

### ISSUE THREAD

**Issue by icommit** [rethinkdb-rs/reql#33]
Here is what I'm trying to accomplish:

1. If a database[with intended db name] does not exist, create a new db
2. Do a multi document insert. I'm talking about inserting something like the following:

{ name: "William Adama", tv_show: "Battlestar Galactica",
      posts: [
        {title: "Decommissioning speech", content: "The Cylon War is long over..."},
        {title: "We are at war", content: "Moments ago, this ship received word..."},
        {title: "The new Earth", content: "The discoveries of the past few days..."}
      ]
    }

Insertion is a much higher priority.

I'm sorry I couldn't follow along with the documentation on crates.io since I don't know if this is just me, but some of the documentation example is not even in rust. For example:
var p = r.connect({
    host: 'localhost',
    port: 28015,
    db: 'marvel'
});
p.then(function(conn).

**Comment by rushmorem** [comment]
> If a database[with intended db name] does not exist, create a new db

ReQL doesn't support this out of the box but it provides the necessary APIs to do it. Particularly `db_list` and `db_create`. You can query the databases currently available and then create if it doesn't exist.

> Do a multi document insert. I'm talking about inserting something like the following

There are 2 ways to do this. You can either use Serde's `json` macro or you can create a struct that implements `Serialize` and `Deserialize` and then convert it to `json` when you insert it. Something like:

```rust
r.db("dbname").table("tablename").insert(json!({
    "name": "William Adama", "tv_show": "Battlestar Galactica",
    "posts": [
        {"title": "Decommissioning speech", "content": "The Cylon War is long over..."},
        {"title": "We are at war", "content": "Moments ago, this ship received word..."},
        {"title": "The new Earth", "content": "The discoveries of the past few days..."}
    ]
}))
```

> I'm sorry I couldn't follow along with the documentation on crates.io since I don't know if this is just me, but some of the documentation example is not even in rust.

You are right. Documentation for most commands isn't in Rust, it's actually JavaScript. The commands are automatically generated from the JS docs. The plan is to parse the examples and convert them to Rust code automatically. I can turn off the documentation for now if it's too confusing.
