### ISSUE TITLE
Example of how to send struct using Arg::into_arg trait

### ISSUE THREAD

**Issue by TotalKrill** [rethinkdb-rs/reql#37]
Would be helpful to know how to implement the trait for a personal struct with mixed member types, i have not yet figured out how to do an insert into my database. 

I saw that 'str' has IntoArg implemented as such i expected 

    let call = r.db("test")
        .table("table")
        .insert( "hello")
        .run::<ServerStatus>(conn).unwrap();

printing call yields: 

    Some(Err(Runtime(QueryLogic("Cannot convert STRING to SEQUENCE"))))

**Comment by rushmorem** [comment]
RethinkDB is a document oriented database. It takes JSON documents, so inserts must be such. To do that, use the [`json` macro from `serde_json`](https://docs.rs/serde_json/1/serde_json/macro.json.html).

For example:-

```rust
let call = r.db("test")
    .table("table")
    .insert(json!({
        "greeting": "hello"
    }))
    .run::<ServerStatus>(conn).unwrap();
```

Using a custom struct is just as easy:-

```rust
#[derive(Serialize, Deserialize)]
struct Message {
    greeting: &'static str,
}

let message = Message {
    greeting: "hello",
};

let call = r.db("test")
    .table("table")
    .insert(json!(message))
    .run::<ServerStatus>(conn).unwrap();
```

Inserts, however, return `WriteStatus` not `ServerStatus` so you will get a `Document::Unexpected`.
